# Generated by Django 4.2.14 on 2024-07-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['order', 'date']},
        ),
        migrations.AddField(
            model_name='event',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('WAITING', '____Waiting____'), ('ACCEPTED', '___Accepted____'), ('REJECTED', '____Rejected'), ('GIVEN_TICKET', '____Given Ticket____')], default='WAITING', max_length=20),
        ),
    ]
